import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Doctor Portal",
  description: "Generated by Doctor Posrtal",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
       <div className="md:px-20">
       <Header />
       {children}
       </div>

      </body>
    </html>
  );
}
